dist: trusty
sudo: required
language: node_js
node_js:
  - "node"
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${GITHUB_PACKAGES_TOKEN}" >> .npmrc
script:
  - npm run build
#  - npm test
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $ARRAY_PIPE_TEST_APP_GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    branch: master
